# Generated by Django 4.0.1 on 2022-01-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('nickname', models.CharField(max_length=50)),
                ('kakao_id', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
